services:
  db:
    image: postgres:16
    container_name: prova-hidrica-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-new:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    container_name: prova-hidrica-backend
    restart: always
    build:
      context: ./src/api/
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DIALECT_DATABASE: ${DIALECT_DATABASE}
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    container_name: prova-hidrica-frontend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - cert:/usr/src/app/cert
    networks:
      - app-network
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: prova-hidrica-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data-new:
  cert:
